services:
  locust:
    build:
      context: ../digital-signature-service-locust-tests
    container_name: locust
    environment:
      - TARGET_HOST=http://localhost:8000
    ports:
      - "8089:8089"
    networks:
      - backend_network
    depends_on:
      - backend
      - db
      - rabbitmq
      - redis

networks:
  backend_network:
    driver: bridge
